### ISSUE TITLE
after merge the size is K. this is completly wrong

### ISSUE THREAD

**Issue by lwclover** [tdebatty/spark-knn-graphs#10]
public NeighborList call(final NeighborList nl1, final NeighborList nl2)
            throws Exception {
        NeighborList nnl = new NeighborList(k);
        nnl.addAll(nl1);
        nnl.addAll(nl2);
        return nnl;
    }

**Comment by tdebatty** [comment]
Hi,

In a k-nn graph, each node has exactly k edges. These are stored in a neighbor list which is (as the documentation says) a bounded list. Hence adding new elements to the neighborlist will indeed keep the k most similar edges, and the size remains k...

**Comment by lwclover** [comment]
thanks for your reply.
the code above the final nnl result is nl1
the second param nl2 can not add in nnl
