### ISSUE TITLE
Handling large amount of data

### ISSUE THREAD

**Issue by zhassanbey** [tdebatty/spark-knn-graphs#6]
The main problem in KNN calculation is the amount data that needs to be broadcasted to each node. For instance, if you have 20 M vectors (~1.3TB), it is really hard to broadcast them in memory. How would you handle this situation?
Thank you in advance.

**Comment by tdebatty** [comment]
Do you mean foor k-nn graphs in general, or specifically for this project?

**Comment by zhassanbey** [comment]
Hi thank you for reply. I mean specifically for this project. But if you have ideas to share, it would be great.

**Comment by tdebatty** [comment]
Hello,

I don't know if you found a solution for your problem? Just thought of this
now: Spark was actually designed for processing datasets that can fit into
the distributed memory. Hence for your kind of problem I would recommend to:
- preprocess or filter your data to reduce its size or
- use some other processing framework, like Hadoop Map Reduce

Hope this can help...

Best regards,

**Comment by zhassanbey** [comment]
Hi tdebatty, 
Thank you for reply.
I am currently doing it by separating the input into chunks. Well, I first "chunkify" the files, then find knn for each chunk by broadcasting the chunk only. After the knn is calculated for the current chunk of files in iteration, I persist that result with MEMORY_DISK strategy. When all the chunks have processed, I try to merge them. The idea works somehow, but I am seeking for more elegant solution.
