### ISSUE TITLE
handle hue data very slow

### ISSUE THREAD

**Issue by lwclover** [tdebatty/spark-knn-graphs#7]
look title

**Comment by tdebatty** [comment]
Hi,

Sorry for the late answer...
What kind of data are you using? And which functions are too slow? Do you have a MWE too illustrate your problem?

**Comment by lwclover** [comment]
thanks for your reply.
here is my test result
One hundred thousand data,each row has 18 cols.
the K set 20 maxiterator is 10
run on 10 producer machine with 100 total cores 4g per executor
then i cat not get final result.
laterly  I change the buckets 20 to 200, then I get the result. but takes 5 mins

**Comment by lwclover** [comment]
Hi,
We're in different hemispheres
I wish you a happy life

**Comment by lwclover** [comment]
I want to change buckets num. do you have any advice?
