### ISSUE TITLE
the iterator is no using.

### ISSUE THREAD

**Issue by lwclover** [tdebatty/spark-knn-graphs#8]
code below
the iterator is no using.max_iterations=1
 for (int iteration = 0; iteration < max_iterations; iteration++) {
            // Reverse
            JavaPairRDD<Node<T>, Node<T>> exploded_graph = graph.flatMapToPair(new ReverseFunction<T>());
            // Update
            graph = exploded_graph.groupByKey().flatMapToPair(new UpdateNLFunction<T>(similarity, k));
            // Filter
            graph = graph.groupByKey().mapToPair(new FilterFunction<T>(k));
        }

**Comment by tdebatty** [comment]
Hi,

max_iterations is simply used to to stop the for loop after a configurable number of iterations...
This is quite standard in java source code.

I slightly modified the test to illustrate this:
https://github.com/tdebatty/spark-knn-graphs/blob/master/spark-knn-graphs/src/test/java/info/debatty/spark/knngraphs/builder/NNDescentTest.java#L87

Will produce will produce something like this:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running info.debatty.spark.knngraphs.builder.NNDescentTest
NNDescent
=========

17/07/20 10:56:37 DEBUG NNDescent: Iteration 0
17/07/20 10:56:37 DEBUG NNDescent: Iteration 1

[Stage 0:>                                                          (0 + 0) / 8]
[Stage 3:====================================>                      (5 + 3) / 8]
[Stage 4:============================================>              (6 + 2) / 8]
                                                                                
((188 => High Qua1ityMedications   Discount On All Reorders = Best Deal Ever! Viagra ...
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.843 sec
```

**Comment by lwclover** [comment]
thank for your reply. 
sorry  you are right
